spring.application.name=demo
spring.datasource.url=jdbc:postgresql://postgres:5432/urlshortener
spring.datasource.username=trndnd
spring.datasource.password=test
spring.jpa.hibernate.ddl-auto=update
server.port=8081