pipeline {
    agent any
    stages {
        stage('Checkout (git checkout)') {
            steps {
                checkout scm
            }
        }
        stage('Install Tools') {
            steps {
                echo 'Installing Minikube and Kubectl...'
                sh '''
                    # Download and install kubectl
                    KUBECTL_VERSION=$(curl -L -s https://dl.k8s.io/release/stable.txt)
                    curl -LO "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl"
                    chmod +x ./kubectl
                    
                    # Download and install minikube
                    curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
                    chmod +x minikube-linux-amd64
                    mkdir -p bin
                    
                    #Moving kubectl and minikube in there respective places
                    mv ./kubectl ./bin/kubectl
                    mv ./minikube-linux-amd64 ./bin/minikube
                '''
            }
        }
        stage('Start Minikube') {
            steps {
                echo 'Starting Minikube using Docker driver...'
                // You must start Minikube so kubectl has a cluster to validate against
                sh 'minikube start --driver=docker'
            }
        }
        stage('Test and validating manifests') {
            steps {
                dir('services/UrLshortener-service') {
                    sh 'kubectl apply --dry-run=client -f k8s'
                }
            }
        }
        stage('Building Image After Testing (Containerising it)') {
            steps {
                sh ' eval $(minikube docker-env) && docker build -t aaronm10/shortener-service:v1 .'
            }
        }
        stage('Pushing Image to Docker') {
            steps {
                sh 'docker push aaronm10/shortener-service:v1 .'
            }
        }

        stage('Completed') {
            steps {
                echo 'Completed'
            }
        }
    }
}